name: Build program

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact for GitHub pages
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages
          path: .
